global:
  domain: argo.breeze-blocks.net
autoscaling:
  enabled: false
certificate:
  enabled: true
fullnameOverride: argo
persistence:
  storageClass: csi-lvm-linear
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true
service:
  port: 8080
serviceAccount:
  create: true
