###
# ```{rubric} Image Values
# ```
# ---
# Describe the image to use for the node.
#
# ```{literalinclude} /monero/values.yaml
# :language: yaml
# :start-at: "image:\n"
# :end-before: "###\n"
# ```
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/sethforprivacy/simple-monerod
  tag: v0.18.3.4@sha256:435a80a7f7cc0a12d05038492e879aa45d6e7eb791ef1327ebff21c205491398

###
# ```{rubric} Monero Node Configuration Values
# ```
# ---
# Configure the monero node that will run on the cluster.
#
# ```{literalinclude} /monero/values.yaml
# :language: yaml
# :start-at: "monero:\n"
# :end-before: "###\n"
# ```
monero:
  enablednsblocklist: true
  noigd: true
  pruneblockchain: true
  publicnode: true
  rpcbindip: 0.0.0.0
  rpcbindport: "18089"

###
# ```{rubric} Image Values
# ```
# ---
# Describe the image to use for the node.
#
# ```{literalinclude} /monero/values.yaml
# :language: yaml
# :start-at: "persistence:\n"
# :end-before: "###\n"
# ```
persistence:
  blockchainstorage:
    enabled: true
    mountPath: /mnt/monero

###
# ```{rubric} Portal Values
# ```
# ---
# Portal configuration values.
#
# ```{literalinclude} /monero/values.yaml
# :language: yaml
# :start-at: "portal:\n"
# :end-before: "###\n"
# ```
portal:
  open:
    enabled: true

###
# ```{rubric} Security Context Values
# ```
# ---
# Security context for the deployment's pod.
#
# ```{literalinclude} /monero/values.yaml
# :language: yaml
# :start-at: "securityContext:\n"
# :end-before: "###\n"
# ```
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

###
# ```{rubric} Service Values
# ```
# ---
# Services for main and rpc ports.
#
# ```{literalinclude} /monero/values.yaml
# :language: yaml
# :start-at: "service:\n"
# ```
service:
  main:
    ports:
      main:
        port: 18080
        protocol: tcp
        targetPort: 18080
  rpc:
    enabled: true
    ports:
      rpc:
        enabled: true
        port: 18089
        protocol: tcp
        targetPort: 18089
