###
# ```{rubric} Annotations
# ```
# ---
# These annotations are used to provide validation for ArtifactHub
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :caption: annotations
# :language: yaml
# :start-at: "annotations:\n"
# :end-before: "###\n"
# ```
annotations:
  artifacthub.io/signKey: |
    fingerprint: 2B8F22F57260EFA67BE1C5824B11F800CD9D2252
    url: https://argoproj.github.io/argo-helm/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: changed
      description: Bump argo-cd to v2.12.1

###
# ```{rubric} API Version
# ```
# ---
# The Helm API version to use for this chart.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "apiVersion: v2\n"
# :end-before: "###\n"
# ```
apiVersion: v2

###
# ```{rubric} App Version
# ```
# ---
# This is the version number of the application being deployed.
# This version number should be incremented each time you make changes to the
# application. Versions are not expected to follow Semantic Versioning.
#
# They should reflect the version the application is using.
#
# It is recommended to use it with quotes.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "appVersion: v2.12.1\n"
# :end-before: "###\n"
# ```
appVersion: v2.12.1

###
# ```{rubric} App Version
# ```
# ---
# This is the version number of the application being deployed.
# This version number should be incremented each time you make changes to the
# application. Versions are not expected to follow Semantic Versioning.
#
# They should reflect the version the application is using.
#
# It is recommended to use it with quotes.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "dependencies:\n"
# :end-before: "###\n"
# ```
dependencies:
- name: redis-ha
  version: 4.26.1
  repository: https://dandydeveloper.github.io/charts/
  condition: redis-ha.enabled

###
# ```{rubric} Description
# ```
# ---
# A brief description of the chart.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.\n"
# :end-before: "###\n"
# ```
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.

###
# ```{rubric} Home URL
# ```
# ---
# The project's home address.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "home: https://github.com/argoproj/argo-helm\n"
# :end-before: "###\n"
# ```
home: https://github.com/argoproj/argo-helm

###
# ```{rubric} Icon URL
# ```
# ---
# The path to the chart's icon.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png\n"
# :end-before: "###\n"
# ```
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png

###
# ```{rubric} Keywords
# ```
# ---
# Keywords for listing the project.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "keywords:\n"
# :end-before: "###\n"
# ```
keywords:
- argoproj
- argocd
- gitops

###
# ```{rubric} Kube Version
# ```
# ---
# Minimum required Kubernetes version.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "kubeVersion: \">=1.25.0-0\"\n"
# :end-before: "###\n"
# ```
kubeVersion: ">=1.25.0-0"

###
# ```{rubric} Maintainers
# ```
# ---
# Contact info for the project's maintainers.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "maintainers:\n"
# :end-before: "###\n"
# ```
maintainers:
- name: argoproj
  url: https://argoproj.github.io/

###
# ```{rubric} Name of the chart
# ```
# ---
# The chart's name.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "name: argo-cd\n"
# :end-before: "###\n"
# ```
name: argo-cd

###
# ```{rubric} Source URLs
# ```
# ---
# LIst of source urls for the project.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "sources:\n"
# :end-before: "###\n"
# ```
sources:
- https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
- https://github.com/argoproj/argo-cd

###
# ```{rubric} Version
# ```
# ---
# The version of the application chart.
#
# ```{literalinclude} /charts/argo-cd/Chart.yaml
# :language: yaml
# :start-at: "version: 7.4.4\n"
# ```
version: 7.4.4
