---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: the-hard-way-int
spec:
  ingressClassName: nginx
  rules:
    - host: argo.breeze-blocks.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: https
  tls:
    - hosts:
        - argo.breeze-blocks.net
      secretName: argocd-server-tls # as expected by argocd-server
