{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{ .Values.service.selectorLabels | toYaml | nindent 4 }}
spec:
  selector:
    {{ .Values.service.selectorLabels | toYaml | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  externalIPs:
    - 192.168.5.40
    - 192.168.5.50
  type: {{ .Values.service.type }}
{{- end -}}
