apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo.fullname" . }}
  labels:
    {{- include "argo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "argo.selectorLabels" . | nindent 4 }}
